### ISSUE TITLE
How can I use it in script with bash functions?

### ISSUE THREAD

**Issue by Casul51** [slavaGanzin/await#1]
```
 ╰─λ cat test.sh 
#!/bin/bash
function func {
echo 2
}
await 'echo 1' -e 'func'

 ╰─λ test.sh 
sh: line 1: func: command not found
⣷ echo 1
```
I've tried to pass function with different approaches, but no result. Is it possible to pass function (without using another scripts.sh files or writing entire commands in await) in my case?

**Comment by slavaGanzin** [comment]
Hi.

Await spawns a separate process for every executed command, this process is not aware of functions you created in your bash script. 

If you want to call function after something awaitable, you can do it like this:
```bash
#!/bin/bash
function func {
  echo 2
}
await 'curl example.com' 'sleep 5' # blocking execution
func #prints 2 after 5 seconds
```

If you want to launch bash function you can do this like:
```
await 'bach -e"source yourfile.bash; func"'
```

**Comment by slavaGanzin** [comment]
https://github.com/Casul51/timetable.sh/blob/main/timetable.sh#L102

I don't get what you want to achieve. So if you'll describe it to me, I can help.
