### ISSUE TITLE
Invalid SSL cert on documentation website

### ISSUE THREAD

**Issue by hongkongkiwi** [slavaGanzin/await#3]
Website documentation certificate problem:
https://await-cli.app/

The documentation website gives me an invalid certificate error:
```
Your connection isn't private
Attackers might be trying to steal your information from await-cli.app (for example, passwords, messages or credit cards).
NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by slavaGanzin** [comment]
@hongkongkiwi Andy, the site is currently down. Just forget about it because of war and all the calamity it brings

**Comment by slavaGanzin** [comment]
Thanks for reporting an issue


But basically info there is the same as in readme.

**Comment by slavaGanzin** [comment]
@hongkongkiwi finally fixed
