### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [slavaGanzin/await#4]
Would you like to add more error handling for return values from functions like the following?
* [fopen](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream") ⇒ [service](https://github.com/slavaGanzin/await/blob/95ede1f7304c36cfc3ae9fe16459077964eba994/await.c#L71)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [replace](https://github.com/slavaGanzin/await/blob/95ede1f7304c36cfc3ae9fe16459077964eba994/await.c#L299)

**Comment by slavaGanzin** [comment]
Hello, Markus. I would love to. But can you explain your use case? Or a situation you get these errors?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by slavaGanzin** [comment]
@elfring you're right this should be fixed. If you have time, please, make PR. Otherwise I'll do it when I have free time.

**Comment by elfring** [comment]
:thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by slavaGanzin** [comment]
@elfring I know nothing about. But if you think it's needed I'm open to any suggestions

**Comment by elfring** [comment]
:thought_balloon: Would you become interested in [aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by slavaGanzin** [comment]
Markus, if you mean to separate everything into some kind of microservices and then exchange messages between them. Yeah, I can see, it can be beneficial, but it's kinda overengineering for a 400 LOC program, don't you think?

**Comment by elfring** [comment]
I am trying to present an other view also for the usage of aspect-oriented programming.

:thought_balloon:
* Can you become aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns?
* [Which development tools can help any more for this software area](https://www.aspectc.org/ "Software development with AspectC++")?

**Comment by slavaGanzin** [comment]
I'm JS/Python developer, I know how to use AOP. But I don't see how this can be beneficial for such a small tool. And I definitely don't want to rewrite everything to some overengineered monster, just to be sure that this is "the right way". Because this tool works, and it suits my needs.

**Comment by elfring** [comment]
>…, I know how to use AOP.

This is good to know.


>But I don't see how this can be beneficial for such a small tool.

:thinking: Further development tools can help to avoid programming mistakes, can't they?


>And I definitely don't want to rewrite everything to some overengineered monster,

:thought_balloon: I hope that advanced methodologies can be taken better into account.


>just to be sure that this is "the right way".

:thought_balloon: It is just safer to [handle also “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?

**Comment by slavaGanzin** [comment]
I’ve talked to chatgpt. Shame on me

**Comment by elfring** [comment]
:bulb: You did not talk with the software “ChatGPT” for this issue.

:thought_balloon: Do you care still for incomplete error detection and improvable exception handling?
