### ISSUE TITLE
Curl und run will never die

### ISSUE THREAD

**Issue by seraphyn** [slavaGanzin/await#7]
`curl https://i.jpillora.com/slavaGanzin/await! | bash`
This should never ever be done.
Make it worse, use | sudo bash

Please do not recommend this procedure

**Comment by slavaGanzin** [comment]
I do agree partly.

But you can review the script before running it: https://i.jpillora.com/slavaGanzin/await!?type=script. But what is a difference of running the script "from internet" and all that mad shell scripts that Ubuntu/Debian distributions use for installing average package? Do you review them as well?


Nevertheless. Will add some eget & nix instructions.

**Comment by slavaGanzin** [comment]
Done
