### ISSUE TITLE
Feature Request: Version flag

### ISSUE THREAD

**Issue by chewblacka** [slavaGanzin/await#8]
Hi, is it possible to add a version flag to the command line switch?
e.g.

    await --version
    1.0.2

Many thanks!

**Comment by slavaGanzin** [comment]
Hi. Sure thing. 

https://github.com/slavaGanzin/await/releases/tag/v1.0.3

**Comment by chewblacka** [comment]
Many thanks!

**Comment by slavaGanzin** [comment]
Thanks for supporting nixpackage!
